Skip to content
 •   train-27e51255 🦴 🐈 github/blob 
✨ Feedback Switch to  Rails 7.1.0.alpha.9646456 | Ruby 3.1.2

Search or jump to...
Pull requests
Issues
Marketplace
Explore
 
@MylesBorins 
MylesBorins
/
myles.dev
Public
Code
Issues
Pull requests
Actions
Projects
Wiki
Security
Insights
Settings
myles.dev/.github/workflows/publish.yml
@MylesBorins
MylesBorins Update publish.yml
Latest commit d86ec61 2 minutes ago
 History
 1 contributor
49 lines (43 sloc)  1.01 KB

name: github pages

on:
  push:
    branches:
    - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Pages
      uses: actions/configure-pages@v1
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
    - run: npm ci
    - run: npm run build
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: './public_html'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
You have unread notifications
